== SISMIOP Service

=== Nama Komponen Layanan Teknis/Pendukung

SISMIOP Service

=== Nama Layanan yang Didukung

Layanan yang didukung oleh komponen ini adalah :

* Portal Pajak Daerah Kabupaten Brebes

=== Referensi SLA (_Service Level Agreement_) yang telah disetujui

Referensi _Service Level Agreement_ (SLA) untuk layanan ini merujuk ke dokumen https://github.com/tamami-bf/2021-sla-layanan-teknis/blob/master/build/sla-layanan-ti.pdf

=== Kemampuan Teknis Tingkat Layanan Saat Ini

Belum ada pengukuran tingkat layanan untuk komponen layanan teknis / pendukung saat ini.

=== Proses Penyediaan Layanan

Proses penyediaan layanan ini dilakukan dengan dokumen Perjanjian Kerjasama antara Badan Pendapatan Daerah Kabupaten Brebes dengan unit kerja lain yang membutuhkan, kemudian Bagian Teknologi Informasi menindaklanjuti dengan memberikan dokumen teknis penggunaan layanan SISMIOP Service.

=== Periode Kajian Terhadap Layanan dan Laporannya

Periode kajian terhadap layanan dilakukan paling cepat setiap triwulan termasuk pembuatan laporannya.

=== Versi dan Tanggal Revisi 

[cols="2,3", width="75%"]
|===
| Versi | Tanggal

| 1.0 | 3 Mei 2021
|===